// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxtpzkxwlrcazbqxegeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4dHB6a3h3bHJjYXpicXhlZ2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTE2OTAsImV4cCI6MjA3MjYyNzY5MH0.ouN9rgDAnyDd_BgNfVLxXmNMoTcYJ18eUlJvYICbKM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});